export const ADD_RECIPE = 'ADD_RECIPE';
export const RECIPE_LOADING = 'RECIPE_LOADING';
export const RECIPE_FAILED = 'RECIPE_FAILED';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const ADD_FEEDBACKS = 'ADD_FEEDBACKS';
export const FEEDBACKS_FAILED = 'FEEDBACKS_FAILED';
export const FEEDBACKS_LOADING = 'FEEDBACKS_LOADING';
export const ADD_SINGLERECIPE = 'ADD_SINGLERECIPE';
export const DELETED_RECIPE = 'DELETED_RECIPE';
export const UPDATE_RECIPE_SUCCESS = 'UPDATE_RECIPE_SUCCESS';
export const FOUNDER_LOADING = 'FOUNDER_LOADING';
export const FOUNDER_FAILED = 'FOUNDER_FAILED';
export const ADD_FOUNDER = 'ADD_FOUNDER';
export const ADD_PROMOTION = 'ADD_PROMOTION';
export const PROMOTION_LOADING = 'PROMOTION_LOADING';
export const PROMOTION_FAILED = 'PROMOTION_FAILED';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';



